config/routes.rb
MoscowCity::Application.routes.draw do
  telegram_webhooks :moscowcity_bot => TelegramWebhooksController

  namespace :admin do
    resources :towers, except: :show do
      collection { post :batch_action }
    end

    resources :offers, except: :show do
      collection { post :batch_action }
      collection { post :image }
    end

    resources :offers_images, only: [:create, :destroy]

    resources :categories, except: :show do
      collection { post :batch_action }
      member { put :drop }
    end

    resources :user_companies, except: :show do
      collection { post :batch_action }
    end

    resources :helps, only: :index
    resource  :settings, only: [:edit, :update]

    resources :users, except: :show do
      collection { post :batch_action }
    end

    resources :versions, only: [:index, :show] do
      collection { post :batch_action }
    end

    resources :inline_attachments, only: :create
    resources :inline_images, only: [:new, :create, :destroy] do
      post 'add_item', on: :collection
    end

    resources :pages, except: :show do
      collection { post :batch_action }
      member { put :drop }
    end

    root to: 'pages#index'
  end

  namespace :ajax do
     resources :offers do
      collection do
        get :table
      end
    end
  end

  scope module: :web do
    # ActiveAdmin.routes(self)
    mount RedactorRails::Engine => 'redactor_rails'


    get :login, to: 'sessions#new'
    get :logout, to: 'sessions#destroy'


    resources :app_demands, only: [:index, :new, :create]
    resource :apps_list, only: [:show], controller: 'apps_list'
    resources :users
    resources :offers, only: [:index] do
      collection do
        get :imports
      end
    end
    resource :profile, only: [:show, :update]
    resource :session, only: [:create] do
      post :get_password
      get :registration, to: 'sessions#registration'
    end
    root to: 'main#show'
  end







  begin
    Page.for_routes.group_by(&:behavior).each do |behavior, pages|
      pages.each do |page|
        case behavior
        when nil
        else
          resource( "#{page.class.name.underscore}_#{page.id}",
                    path:       page.absolute_path,
                    controller: behavior,
                    only:       :show,
                    page_id:    page.id )
        end
      end
    end
  rescue
    nil
  end
end

app/views/layouts/material/_contacts.haml
.card
  .card-header
    %h2
      Контакты
      %small
        Информация для связи с нами
  .card-body.card-padding
    .pmo-contact
      %ul
        %li.ng-binding
          %i.zmdi.zmdi-phone
          +7(985)065-89-98
        %li.ng-binding
          %i.zmdi.zmdi-email
          = link_to 'offers@moscitytowers.ru', 'mailto:offers@moscitytowers.ru'
        %li.ng-binding
          %i.zmdi.zmdi-facebook-box
          = link_to 'mibc.moscowcity', 'https://www.facebook.com/500011350187436'

        %li
          %i.zmdi.zmdi-pin
          %address.m-b-0.ng-binding
            Пресненская набережная 8с1
        = link_to 'https://www.google.ru/maps/@55.7486061,37.5396504,15.96z', target: '_blank', class: "pmo-map" do
          = image_tag "/img/map.jpg"

app/views/layouts/material/_footer.haml
%footer#footer
  Moscow City Towers LLC

app/views/layouts/material/_header.haml
%header#header.clearfix{"data-ma-theme" => "bluegray"}
  %ul.h-inner
    %li.hi-trigger.ma-trigger{"data-ma-action" => "sidebar-open", "data-ma-target" => "#sidebar"}
      .line-wrap
        .line.top
        .line.center
        .line.bottom
    %li.hi-logo.hidden-xs
      = link_to 'Moscow City Towers', root_path
  .text-right
    = link_to "tel:79850658998", "+7 (985) 065-89-98"

app/views/layouts/material/_sidebar.slim
aside#sidebar.sidebar.c-overflow
  .s-profile
    a data-ma-action="profile-menu-toggle" href=""
      .sp-pic
        img alt="" src=current_user.avatar_url
      .sp-info
        = current_user.full_name
        i.zmdi.zmdi-caret-down
      ul.main-menu
        li
          = link_to profile_path  do
            i.zmdi.zmdi-account
            = t('.profile')
        li
          = link_to logout_path do
            i.zmdi.zmdi-time-restore
            = t('.exit')


  ul.main-menu
    - if current_user.admin?
      li.sub-menu
        a data-ma-action="submenu-toggle" href=""
          i.zmdi.zmdi-view-list
          | Администрирование
        ul
          li
            = link_to 'Пользователи', users_path
            = link_to 'Предложения', offers_path
        ul
          li
            = link_to 'Настройка сайта', '#'
    - if can?(:index, AppDemand)
      li
        = link_to apps_list_path do
          i.zmdi.zmdi-assignment
          | Список заявок
    - if can? :create, AppDemand
     li.sub-menu
        a data-ma-action="submenu-toggle" href=""
          i.zmdi.zmdi-assignment-returned
          | Создать заявку
        ul
          li
            = link_to 'Спрос', new_app_demand_path



    - if can?(:analytic, AppDemand)
      li
        = link_to app_demands_path do
          i.zmdi.zmdi-shield-security
          | Смарт-контракты(скоро)