config/routes.rb
MoscowCity::Application.routes.draw do
  telegram_webhooks :moscowcity_bot => TelegramWebhooksController

  namespace :admin do
    resources :towers, except: :show do
      collection { post :batch_action }
    end

    resources :offers, except: :show do
      collection { post :batch_action }
      collection { post :image }
    end

    resources :offers_images, only: [:create, :destroy]

    resources :categories, except: :show do
      collection { post :batch_action }
      member { put :drop }
    end

    resources :user_companies, except: :show do
      collection { post :batch_action }
    end

    resources :helps, only: :index
    resource  :settings, only: [:edit, :update]

    resources :users, except: :show do
      collection { post :batch_action }
    end

    resources :versions, only: [:index, :show] do
      collection { post :batch_action }
    end

    resources :inline_attachments, only: :create
    resources :inline_images, only: [:new, :create, :destroy] do
      post 'add_item', on: :collection
    end

    resources :pages, except: :show do
      collection { post :batch_action }
      member { put :drop }
    end

    root to: 'pages#index'
  end

  namespace :ajax do
     resources :offers do
      collection do
        get :table
      end
    end
  end

  scope module: :web do
    # ActiveAdmin.routes(self)
    mount RedactorRails::Engine => 'redactor_rails'


    get :login, to: 'sessions#new'
    get :logout, to: 'sessions#destroy'


    resources :app_demands, only: [:index, :new, :create]
    resource :apps_list, only: [:show], controller: 'apps_list'
    resources :users
    resources :offers, only: [:index] do
      collection do
        get :imports
      end
    end
    resource :profile, only: [:show, :update]
    resource :session, only: [:create] do
      post :get_password
      get :registration, to: 'sessions#registration'
    end
    root to: 'main#show'
  end







  begin
    Page.for_routes.group_by(&:behavior).each do |behavior, pages|
      pages.each do |page|
        case behavior
        when nil
        else
          resource( "#{page.class.name.underscore}_#{page.id}",
                    path:       page.absolute_path,
                    controller: behavior,
                    only:       :show,
                    page_id:    page.id )
        end
      end
    end
  rescue
    nil
  end
end

app/models/app_demand.rb
class AppDemand < ActiveRecord::Base
  extend Enumerize

  belongs_to :tower
  belongs_to :user
  belongs_to :client, class_name: 'User'
  belongs_to :deal_profile, polymorphic: true
  belongs_to :property_profile, polymorphic: true

  enumerize :type_of_deal, in: [:to_buy, :for_rent]
  enumerize :type_of_property, in: [:apartment, :office]
  enumerize :decorated, in: [:any, :yes, :no], default: :any
  enumerize :furniture, in: [:any, :yes, :no], default: :any

  accepts_nested_attributes_for :client, :deal_profile, :property_profile

  scope :sorted, -> { order('created_at DESC') }

  belongs_to :tower
  validates :user, presence: true






end

app/models/app_demand/deal_for_rent_profile.rb
class AppDemand::DealForRentProfile < ActiveRecord::Base
  extend Enumerize

  has_one :app_demand, :as => :deal_profile

  enumerize :rent_duration, in: [:few_months, :from_3_to_6, :from_6_to_year, :more_year]
end

app/models/app_demand/deal_to_buy_profile.rb
class AppDemand::DealToBuyProfile < ActiveRecord::Base

  has_one :app_demand, :as => :deal_profile

end

app/models/app_demand/property_apartment_profile.rb
class AppDemand::PropertyApartmentProfile < ActiveRecord::Base
  has_one :app_demand, :as => :property_profile
end

app/models/app_demand/property_office_profile.rb
class AppDemand::PropertyOfficeProfile < ActiveRecord::Base
  extend Enumerize

  has_one :app_demand, :as => :property_profile

  enumerize :open_space, in: [:any, :yes, :no], default: :any
end

app/controllers/web/app_demands_controller.rb
class Web::AppDemandsController < Web::ApplicationController

  def new
    @form = AppDemandForm.new(AppDemand.new)
  end

  def create
    @form = AppDemandForm.new(current_user.app_demands.new)
    if @form.validate(params[:app_demand].permit!) && @form.prepopulate! && @form.save
      f(:success)
      redirect_to url_for(action: :index)
    else
      f(:error)
      render :new
    end
  end
end

app/views/web/app_demands/_form.haml
- content_for :javascripts do
  :javascript
    $(document).on('change','#app_demand_type_of_deal',function(){
      $('.deal-profile-content>div').addClass('hidden');
      $('.deal-profile-content #'+$(this).val()).removeClass('hidden');
    })

    $(document).on('change','#app_demand_type_of_property',function(){
      $('.property-profile-content>div').addClass('hidden');
      $('.property-profile-content #'+$(this).val()).removeClass('hidden');
    })


= simple_form_for @form,  wrapper: :material do |f|

  = f.simple_fields_for :client_attributes, @form.client, wrapper: :material do |ff|
    .row
      .col-md-4
        = ff.input :full_name, label: 'Имя контактного лица', placeholder: 'напр: Василий Иванов', required: true
      .col-md-4
        = ff.input :phone, label: 'Телефон', input_html: { 'data-mask' => '+7(999)999-99-99' }, required: true
      .col-md-4
        = ff.input :email, as: :email, label: 'E-mail', required: true
      .col-md-4
        = ff.input :site, label: 'Сайт'
      .col-md-4
      .col-md-4
        = ff.input :client_role, label: 'Вид сотрудничества', as: :select, collection: User.client_role.options, include_blank: false
  %br
  %br
  .row
    .col-md-4
      = f.input :type_of_deal, collection: AppDemand.type_of_deal.options, include_blank: false, required: true
    .col-md-4
      = f.input :type_of_property, collection: AppDemand.type_of_property.options, include_blank: false, required: true
    .col-md-4
      = f.input :tower_id, collection: Tower.all, include_blank: 'Не имеет значения', label: 'Башня'
  .row
    .col-md-4
      = f.input :view
    .col-md-4
      = f.input :decorated,  collection: AppDemand.decorated.options, include_blank: false
    .col-md-4
      = f.input :furniture, collection: AppDemand.furniture.options, include_blank: false
  %br
  .row
    .col-md-3
      = f.input :floor_min
    .col-md-3
      = f.input :floor_max
    .col-md-3
      = f.input :min_area
    .col-md-3
      = f.input :max_area
  %br
  .row
    .col-md-6
      .deal-profile-content
        #to_buy
          = f.fields_for :to_buy_attributes, wrapper: :material do |ff|
            = ff.input :max_cost, as: :string, input_html: { 'data-mask' => '000.000.000.000.000,00' }
            %br
            = ff.input :max_cost_per_metr, as: :string, input_html: { 'data-mask' => '000.000.000.000.000,00' }
            = ff.input :time_info
        #for_rent.hidden
          = f.fields_for :for_rent_attributes, wrapper: :material do |ff|
            .row
              .col-md-6
                = ff.input :first_rent_start_at, as: :string, input_html: { 'data-mask' => '00/00/0000', placeholder: 'напр: 23/05/2017'}
              .col-md-6
                = ff.input :last_rent_start_at, as: :string, input_html: { 'data-mask' => '00/00/0000' }
            %br
            = ff.input :rent_duration do
              - opts = AppDemand::DealForRentProfile.rent_duration.values.inject({}) { |sum,k| sum[I18n.t("enumerize.app_demand.deal_for_rent_profile.rent_duration.#{k}")] = k; sum}

              = ff.select :rent_duration, opts, {}, class: 'select optional form-control'
            = ff.input :max_cost_per_month, as: :string, input_html: { 'data-mask' => '000.000.000.000.000,00' }
            = ff.input :max_cost_per_m2_year, as: :string, input_html: { 'data-mask' => '000.000.000.000.000,00' }
    .col-md-6
      .property-profile-content
        #apartment.hidden
          = f.fields_for :apartment_attributes, wrapper: :material do |ff|
            = ff.input :min_rooms_count
        #office
          = f.fields_for :office_attributes, wrapper: :material do |ff|
            .row
              .col-md-6
                = ff.input :min_cabinets_count
              .col-md-6
                = ff.input :max_cabinets_count
            .row
              .col-md-6
                = ff.input :min_negotiation_count
              .col-md-6
                = ff.input :max_negotiation_count

            = ff.input :open_space do
              - opts = AppDemand::PropertyOfficeProfile.open_space.values.inject({}) { |sum,k| sum[I18n.t("enumerize.app_demand.property_office_profile.open_space.#{k}")] = k; sum}
              = ff.select :open_space, opts, {}, class: 'select optional form-control'
    .text-right
      = f.button :submit, 'Отправить', style: 'margin-right: -20px;'
      %br
      %br


-#
  = simple_form_for @form, url: '', wrapper: :form_signin, html: { class: 'form-signin' } do |f|
    h2 class="form-signin-heading" Вход
    .login-wrap
      .user-login-info
        = f.input :email, placeholder: 'E-mail', input_html: { class: 'form-control' }
        = f.input :password, placeholder: 'Пароль', input_html: { class: 'form-control' }
        - if @telegram_account.present?
          = hidden_field_tag :telegram_token, params[:telegram_token]
          .text-center.text-warning
            = "Авторизуйтесь, чтобы привязать аккаунт #{@telegram_account.username}"

      = f.button :submit, 'Войти', class: 'btn btn-lg btn-login btn-block'

app/views/web/app_demands/_nav.slim
ul.tab-nav.tn-justified
  li class="#{ action_name == 'index' && 'active' }"
    =link_to 'Список', users_path
  li class="#{ %w(new create).include?(action_name) && 'active'}"
    =link_to 'Добавить', new_user_path

app/views/web/app_demands/create.html.erb
<h1>Web::AppDemands#create</h1>
<p>Find me in app/views/web/app_demands/create.html.erb</p>

app/views/web/app_demands/index.slim
.card
  .card-header
    h2
      | Заявки на поиск
      small
        | все запросы должны попадать сюда

  = bootstrap_flash
  = render 'nav'
  = render 'list'

app/views/web/app_demands/new.slim
.card
  .card-header
    h2
      | Новая заявка
      small
        | на поиск

  = bootstrap_flash
  .card-body.card-padding
    = render partial: 'form'